"""Incident and audit persistence.

PostgreSQL when DATABASE_URL is set (in-cluster). SQLite otherwise (local/dev/tests).
"""

from __future__ import annotations

import json
import logging
import sqlite3
import threading
import time
from collections.abc import Iterator, Mapping
from contextlib import contextmanager, nullcontext
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

from app import config

log = logging.getLogger("alert-processor.db")

_lock = threading.Lock()
_initialized = False
_pool = None

_SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fingerprint TEXT NOT NULL UNIQUE,
    group_key TEXT,
    status TEXT NOT NULL,
    alertname TEXT,
    namespace TEXT,
    severity TEXT,
    payload_json TEXT NOT NULL,
    recommendation_json TEXT,
    action_result TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_notified_at TEXT
);
CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    incident_id INTEGER,
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    detail TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(incident_id) REFERENCES incidents(id)
);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_updated ON incidents(updated_at);
"""

_POSTGRES_DDL = """
CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint TEXT NOT NULL UNIQUE,
    group_key TEXT,
    status TEXT NOT NULL,
    alertname TEXT,
    namespace TEXT,
    severity TEXT,
    payload_json TEXT NOT NULL,
    recommendation_json TEXT,
    action_result TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_notified_at TEXT
);
CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER,
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    detail TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(incident_id) REFERENCES incidents(id)
);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_updated ON incidents(updated_at);
"""


def _postgres() -> bool:
    url = config.DATABASE_URL.lower()
    return url.startswith("postgres://") or url.startswith("postgresql://")


def describe() -> str:
    if _postgres():
        parsed = urlparse(config.DATABASE_URL)
        host = parsed.hostname or "postgres"
        dbname = (parsed.path or "/").lstrip("/") or "app"
        return f"postgres://{host}/{dbname}"
    return str(config.DB_PATH)


def _conninfo() -> str:
    url = config.DATABASE_URL
    if "sslmode=" not in url.lower():
        url += ("&" if "?" in url else "?") + "sslmode=require"
    return url


def _q(sql: str) -> str:
    if _postgres():
        return sql
    return sql.replace("%s", "?")


def _sqlite_connect() -> sqlite3.Connection:
    config.DATA_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(config.DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


@contextmanager
def _conn() -> Iterator[Any]:
    if _postgres():
        if _pool is None:
            raise RuntimeError("database pool is not initialized")
        with _pool.connection() as conn:
            yield conn
            conn.commit()
        return
    conn = _sqlite_connect()
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def _ensure_pool() -> None:
    global _pool
    if _pool is not None:
        return
    from psycopg.rows import dict_row
    from psycopg_pool import ConnectionPool

    _pool = ConnectionPool(
        conninfo=_conninfo(),
        min_size=1,
        max_size=8,
        timeout=30,
        kwargs={"row_factory": dict_row, "autocommit": False},
        open=True,
    )


def _apply_schema(conn: Any) -> None:
    if not _postgres():
        conn.executescript(_SQLITE_DDL)
        return
    for statement in (part.strip() for part in _POSTGRES_DDL.split(";")):
        if statement:
            conn.execute(statement)


def init() -> None:
    global _initialized
    with _lock:
        if _initialized:
            return
        last_error: Exception | None = None
        for attempt in range(1, 31):
            try:
                if _postgres():
                    _ensure_pool()
                with _conn() as conn:
                    _apply_schema(conn)
                _initialized = True
                log.info("database ready (%s)", describe())
                return
            except Exception as exc:
                last_error = exc
                log.warning("database init attempt %s/30 failed: %s", attempt, exc)
                time.sleep(2)
        raise RuntimeError(f"database init failed: {last_error}") from last_error


def ping() -> bool:
    try:
        with _conn() as conn:
            conn.execute("SELECT 1")
        return True
    except Exception:
        log.exception("database ping failed")
        return False


def _row_to_dict(row: Mapping[str, Any] | None) -> dict[str, Any] | None:
    if row is None:
        return None
    item = dict(row)
    for key in ("payload_json", "recommendation_json"):
        raw = item.get(key)
        if raw:
            try:
                item[key.replace("_json", "")] = json.loads(raw)
            except json.JSONDecodeError:
                item[key.replace("_json", "")] = None
        else:
            item[key.replace("_json", "")] = None
    return item


def get_by_fingerprint(fingerprint: str) -> dict[str, Any] | None:
    with _conn() as conn:
        row = conn.execute(
            _q("SELECT * FROM incidents WHERE fingerprint = %s"), (fingerprint,)
        ).fetchone()
        return _row_to_dict(row)


def get_by_id(incident_id: int) -> dict[str, Any] | None:
    with _conn() as conn:
        row = conn.execute(
            _q("SELECT * FROM incidents WHERE id = %s"), (incident_id,)
        ).fetchone()
        return _row_to_dict(row)


def list_incidents(status: str | None = None, limit: int = 100) -> list[dict[str, Any]]:
    with _conn() as conn:
        if status:
            rows = conn.execute(
                _q(
                    "SELECT * FROM incidents WHERE status = %s ORDER BY updated_at DESC LIMIT %s"
                ),
                (status, limit),
            ).fetchall()
        else:
            rows = conn.execute(
                _q("SELECT * FROM incidents ORDER BY updated_at DESC LIMIT %s"),
                (limit,),
            ).fetchall()
        return [_row_to_dict(r) for r in rows if r is not None]


def upsert_incident(
    *,
    fingerprint: str,
    group_key: str,
    status: str,
    alertname: str,
    namespace: str,
    severity: str,
    payload: dict[str, Any],
) -> dict[str, Any]:
    now = _now()
    payload_json = json.dumps(payload)
    sql = """
        INSERT INTO incidents (
            fingerprint, group_key, status, alertname, namespace,
            severity, payload_json, created_at, updated_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (fingerprint) DO UPDATE SET
            group_key = excluded.group_key,
            status = excluded.status,
            alertname = excluded.alertname,
            namespace = excluded.namespace,
            severity = excluded.severity,
            payload_json = excluded.payload_json,
            updated_at = excluded.updated_at
    """
    with _write_lock():
        with _conn() as conn:
            conn.execute(
                _q(sql),
                (
                    fingerprint,
                    group_key,
                    status,
                    alertname,
                    namespace,
                    severity,
                    payload_json,
                    now,
                    now,
                ),
            )
            row = conn.execute(
                _q("SELECT * FROM incidents WHERE fingerprint = %s"), (fingerprint,)
            ).fetchone()
            return _row_to_dict(row) or {}


def save_recommendation(incident_id: int, recommendation: dict[str, Any]) -> None:
    with _write_lock():
        with _conn() as conn:
            conn.execute(
                _q(
                    """
                    UPDATE incidents
                    SET recommendation_json = %s, updated_at = %s
                    WHERE id = %s
                    """
                ),
                (json.dumps(recommendation), _now(), incident_id),
            )


def mark_notified(incident_id: int) -> None:
    with _write_lock():
        with _conn() as conn:
            conn.execute(
                _q(
                    "UPDATE incidents SET last_notified_at = %s, updated_at = %s WHERE id = %s"
                ),
                (_now(), _now(), incident_id),
            )


def set_status(incident_id: int, status: str, action_result: str | None = None) -> None:
    with _write_lock():
        with _conn() as conn:
            if action_result is None:
                conn.execute(
                    _q("UPDATE incidents SET status = %s, updated_at = %s WHERE id = %s"),
                    (status, _now(), incident_id),
                )
            else:
                conn.execute(
                    _q(
                        """
                        UPDATE incidents
                        SET status = %s, action_result = %s, updated_at = %s
                        WHERE id = %s
                        """
                    ),
                    (status, action_result, _now(), incident_id),
                )


def add_audit(incident_id: int | None, action: str, actor: str, detail: str = "") -> None:
    with _write_lock():
        with _conn() as conn:
            conn.execute(
                _q(
                    """
                    INSERT INTO audit_log (incident_id, action, actor, detail, created_at)
                    VALUES (%s, %s, %s, %s, %s)
                    """
                ),
                (incident_id, action, actor, detail, _now()),
            )


def parse_iso(ts: str | None) -> datetime | None:
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts)
    except ValueError:
        return None


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write_lock():
    return _lock if not _postgres() else nullcontext()
